package codepr

// Pull-request provenance — building the honest, reviewer-facing title, body,
// and a safe, unique head-branch name for a coding run's PR. All pure and
// unit-tested. The body is deliberately transparent (Requirement 7.5): it states
// the agent authored it on a human's behalf, what changed, what was verified
// (and what was NOT — no tests / partial scope / draft), and surfaces any
// scope-judge concern, so a reviewer has full context and calibrated trust.

import (
	"fmt"
	"regexp"
	"strings"
)

// PRProvenance is the input to the body/title builders: everything the reviewer
// should know about how the change was produced and checked.
type PRProvenance struct {
	AgentName      string
	RequestedBy    string // display name of the human who asked (empty for scheduled)
	Task           string // the original instruction
	Repo           RepoRef
	DiffStat       DiffStat
	Verifier       VerifierReport
	Verdict        Verdict // scope-judge verdict (Concern non-empty => flagged)
	Draft          bool    // opened as a draft (e.g. couldn't reach green)
	WholeRepo      bool
	CandidateCount int // whole-repo: how many files the selector matched
}

// BuildPRTitle renders a concise, conventional PR title from the task. It trims
// to a sane length and strips newlines. Never empty (falls back to a generic
// title). Pure.
func BuildPRTitle(task string) string {
	t := strings.TrimSpace(strings.ReplaceAll(task, "\n", " "))
	t = collapseSpaces(t)
	if t == "" {
		return "Automated change"
	}
	// Take the first sentence-ish clause, capped.
	const maxLen = 72
	if len(t) > maxLen {
		t = strings.TrimSpace(t[:maxLen])
		if i := strings.LastIndexByte(t, ' '); i > 20 {
			t = t[:i]
		}
		t += "…"
	}
	return t
}

// BuildPRBody renders the provenance-rich Markdown body. Pure and deterministic
// so it is testable and reproducible.
func BuildPRBody(p PRProvenance) string {
	var b strings.Builder

	// Provenance line.
	author := strings.TrimSpace(p.AgentName)
	if author == "" {
		author = "An AI teammate"
	}
	if rb := strings.TrimSpace(p.RequestedBy); rb != "" {
		fmt.Fprintf(&b, "_Opened by **%s** on behalf of **%s**._\n\n", author, rb)
	} else {
		fmt.Fprintf(&b, "_Opened by **%s**._\n\n", author)
	}

	// The task.
	if task := strings.TrimSpace(p.Task); task != "" {
		b.WriteString("### Task\n")
		b.WriteString(task)
		b.WriteString("\n\n")
	}

	// What changed.
	b.WriteString("### Changes\n")
	fmt.Fprintf(&b, "- %d file(s) changed, +%d / -%d\n", p.DiffStat.Files, p.DiffStat.Added, p.DiffStat.Removed)
	if p.WholeRepo && p.CandidateCount > 0 {
		fmt.Fprintf(&b, "- Whole-repo task: %d candidate file(s) considered\n", p.CandidateCount)
	}
	if p.DiffStat.PartialScope {
		b.WriteString("- ⚠️ Partial scope: this is a large repository and only the most relevant files were changed; related code may remain.\n")
	}
	b.WriteString("\n")

	// Verification — honest about what ran and what didn't.
	b.WriteString("### Verification\n")
	if len(p.Verifier.Ran) == 0 {
		b.WriteString("- No verifiers ran (no recognized build system detected).\n")
	} else {
		for _, v := range p.Verifier.Ran {
			mark := "✅"
			if !v.Passed {
				mark = "❌"
			}
			name := strings.TrimSpace(v.Name)
			if name == "" {
				name = string(v.Kind)
			}
			fmt.Fprintf(&b, "- %s %s\n", mark, name)
		}
		if !p.Verifier.HadTests {
			b.WriteString("- ⚠️ No tests were present to run — behavior was not verified by tests.\n")
		}
	}
	if p.Draft {
		b.WriteString("- ⚠️ Opened as a **draft**: the change could not be fully verified. Review carefully before merging.\n")
	}
	b.WriteString("\n")

	// Scope-judge concern, if any.
	if concern := strings.TrimSpace(p.Verdict.Concern); concern != "" && !p.Verdict.InScope {
		b.WriteString("### ⚠️ Scope review\n")
		b.WriteString("An automated scope check flagged a possible concern:\n\n> ")
		b.WriteString(concern)
		b.WriteString("\n\n")
	}

	b.WriteString("---\n")
	b.WriteString("_This pull request was generated by an AI teammate and is awaiting human review. It has not been merged._")
	return b.String()
}

// branchSlugRe keeps only branch-safe characters; everything else becomes a dash.
var branchSlugRe = regexp.MustCompile(`[^a-z0-9]+`)

// BuildHeadBranch builds a fresh, safe, unique head branch name from the task
// and a caller-supplied uniqueness suffix (e.g. a short run id). Always prefixed
// so agent branches are recognizable and never collide with human branches, and
// never equal to a base branch. Pure.
func BuildHeadBranch(task, uniqueSuffix string) string {
	slug := branchSlugRe.ReplaceAllString(strings.ToLower(strings.TrimSpace(task)), "-")
	slug = strings.Trim(slug, "-")
	const maxSlug = 40
	if len(slug) > maxSlug {
		slug = strings.Trim(slug[:maxSlug], "-")
	}
	if slug == "" {
		slug = "change"
	}
	suffix := branchSlugRe.ReplaceAllString(strings.ToLower(strings.TrimSpace(uniqueSuffix)), "")
	if suffix == "" {
		suffix = "0"
	}
	if len(suffix) > 12 {
		suffix = suffix[:12]
	}
	return fmt.Sprintf("onecamp-agent/%s-%s", slug, suffix)
}

// collapseSpaces reduces runs of whitespace to single spaces. Pure.
func collapseSpaces(s string) string {
	return strings.Join(strings.Fields(s), " ")
}
